### ISSUE TITLE
Moving presentations to different directory

### ISSUE THREAD

**Issue by EiffL** [modichirag/flowpm#39]
Due to the fact that we host the 2 FlowPM presentations on this repo, it's quite big, and slow to download. We could move these talks elsewhere, and erase them from the git history, making the whole repo a lot more lightweight. 
@modichirag do you think there are some hardcoded links somewhere to the slides you presented at the NERSC meeting?
My talk I can move to my personal talks repo.

**Comment by modichirag** [comment]
I think we can go ahead with this
My talk is here - https://github.com/modichirag/talks/tree/master/LBNL2019
and can be viewed here - https://modichirag.github.io/talks/LBNL2019/#/

**Comment by EiffL** [comment]
Great, I'm removing all of this from the git history, that should make the repo a lot leaner

**Comment by EiffL** [comment]
I *think* it should have worked.... looks like the whole thing is now 5mb... Hopefully I didn't break anyhing ^^'
