### ISSUE TITLE
Return field equal to 1

### ISSUE THREAD

**Issue by EiffL** [modichirag/flowpm#4]
For some reason, when increasing nc to 64, the field I get out of the nbody sim is equal to 1 everywhere. @modichirag this sounds very much like the issue I had on colab recently, you fixed it I don't know how, do you remember that?

**Comment by modichirag** [comment]
Solved here
https://github.com/modichirag/flowpm/commit/c5c60b2d613818bcb1f4b17234361bdf2b312f02
