### ISSUE TITLE
How to specify the code to run with NVIDIA GPU?

### ISSUE THREAD

**Issue by yaojian95** [modichirag/flowpm#44]
Hi,  thank you for your effort to utilize TF,  do your code perform better on GPU than CPU?
If so, how should I run the code on GPUs on a cluster without slurm management system ?

**Comment by EiffL** [comment]
Hi @yaojian95 Sorry for the very very very slow response. If you are still interested in the answer, you can do it manually using MPI to start as many TensorFlow processes as you have GPUs.
Below is a script that should you allow you to start several Client Tensorflow processes, that can then be accessed by another script:
```python
from mpi4py import MPI
import mesh_tensorflow as mtf
import tensorflow as tf
import os
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

FLAGS = None

def main(_):

  # Get MPI rank, we assume one process by node
  comm = MPI.COMM_WORLD
  rank = comm.Get_rank()
  print(comm.size, rank)
  
  mesh_hosts = ["localhost:%d"%(8222+j) for j in range(comm.size)]

  if rank ==0 :
      print(mesh_hosts)

  # Create a cluster from the mesh hosts.
  cluster = tf.train.ClusterSpec({"mesh": mesh_hosts, "master":["localhost:8488"]})

  # Create a server for local mesh members
  server = tf.train.Server(cluster,
                           job_name="mesh",
                           task_index=rank)

  # Only the master job takes care of the graph building
  server.join()
  
if __name__ == "__main__":
  tf.app.run(main=main)
```
Here this is a script for a single machine, but you can adapt it to your cluster configuration, by changing the references to `localhost` appropriately. Then it can be started with something like
```bash
$ mpirun python start_cluster.py
```
after this is run, all TensorFlow processes that you have started will be on standby. In your main mesh-tensorflow script, you can connect to them with:
```python
# List all of your started processes
mesh_hosts = ["localhost:%d"%(8222+j) for j in range(4)]
# Create a cluster from the mesh hosts.                                                                                                                                                                                                                                                                                                                                  
cluster = tf.train.ClusterSpec({"mesh": mesh_hosts, "master":["localhost:8488"]})
# List devices
devices = ["/job:mesh/task:%d"%i for i in range(cluster.num_tasks("mesh"))]

# [.... some stuff happens ....]

mesh_impl = mtf.placement_mesh_impl.PlacementMeshImpl(
    mesh_shape, layout_rules, devices)
lowering = mtf.Lowering(graph, {mesh:mesh_impl})

tf_field = lowering.export_to_tf_tensor(final_field)

with tf.Session("grpc://localhost:8488") as sess:
   fin = sess.run(tf_field)
```
Again, this would need to be adapted to your cluster configuration, i.e. replacing if necessary the `localhost` if you have several machines.

Do let us know if that makes sense, but in any case, we are making a note to document this process, as this will be useful in many circumstances.

**Comment by yaojian95** [comment]
Thanks @EiffL for the detailed code. I will try that and let you know if anything particular happens.
