### ISSUE TITLE
Seed differs from previous code

### ISSUE THREAD

**Issue by modichirag** [modichirag/flowpm#7]
The same seed generates different IC for this version of the code than the fastpm, which was consistent with the old version of flowpm.
Following is an image showing this.

https://files.slack.com/files-pri/TD19RFPCM-FNUBPPCP7/image.png
![image](https://user-images.githubusercontent.com/13356766/65807236-439d8a80-e142-11e9-9ace-b73d1ca34097.png)

**Comment by EiffL** [comment]
Hum... did you change the code? because I removed the argument for the seed .... so I don't know how you specify it...

**Comment by EiffL** [comment]
Can you write a test for it ? Or at least document here the code you use to make this plot? Because looking at the esource code, it should work

**Comment by EiffL** [comment]
The thing that may be different though is whether the graph gets reused several times, the random_normal op is stateful, so it doesn't restart at the seed at the second execution

**Comment by modichirag** [comment]
So you are right in that successive - sess.run(IC) will generate different IC in the same session.
So we need to evaluate IC and final field in the same call
The combination of global+operation level seed is deterministic in the sense that if the graph is not changed, different sessions with the same order of execution will generate same series of IC

I don't see any way of generating the same IC in different run calls in the same session.
Maybe we don't need it?

If one wants, I am ok in closing this issue in that I understand what is happening here now, I am not sure how much I like it though. Maybe will come back to it later :)

Leaving this here since it has some good discussion on this
https://stackoverflow.com/questions/51249811/reproducible-results-in-tensorflow-with-tf-set-random-seed

**Comment by EiffL** [comment]
I think this is a perfectly reasonable behavior. Otherwise we would need to use some non-stateful random operator, but then everytime you draw a batch of sims you get back the same thing, I don't think that's super useful.

I'm going to go ahead and close it for now :-) But we will have to revisit the question soon, in the context of the Mesh implementation, where it's going to be trickier to make sure we control the seed for each slice of the field
